### ISSUE TITLE
Extension Kit extension support for Xcode14

### ISSUE THREAD

**Issue by freddi-kit** [yonaskolb/XcodeGen#1224]
(I'll work for it, this issue is for notifying to other developer)

Currently, we cannot create some new extensions from Xcode15 (e,g, App Intents). It is because the product type is new from Xcode 15 and XcodeGen does not create appropriate copy phase for this new product type.

**Comment by alessionossa** [comment]
Unless you have access to a super-early-beta of next-year release of Xcode, I think you are referring to Xcode 14.

**Comment by freddi-kit** [comment]
@alessionossa Thank you. Actually I'm asking my coworker to handle it. Also, it requires to change tuist/XcodeProj repo code and wait it for releasing new version. So please wait a moment 🙇

**Comment by alessionossa** [comment]
I see that support for _ExtensionKit_ extensions has already been added there https://github.com/tuist/XcodeProj/issues/687.

**Comment by freddi-kit** [comment]
Yes but we need to wait tuist to release new version

**Comment by alessionossa** [comment]
https://github.com/tuist/XcodeProj/releases/tag/8.8.0 🎉

**Comment by freddi-kit** [comment]
We are preparing it, please wait a moment

**Comment by yonaskolb** [comment]
Resolved by https://github.com/yonaskolb/XcodeGen/pull/1228 and released in 2.30.0 👍

**Comment by freddi-kit** [comment]
No, it is still not solved because it is necessary to customize copy framework path for extension kit.

**Comment by yonaskolb** [comment]
Ok cool, didn't know. Are you still going to work on that @freddi-kit? That would be great

**Comment by freddi-kit** [comment]
@yonaskolb my coworker @mtj0928 now published PR, we can review it

**Comment by alessionossa** [comment]
Where can we expect a new release with the actual support for Extension Kit extensions?

**Comment by alessionossa** [comment]
To completely support ExtensionKit Extension, I think we are still missing the correct project configuration to import Frameworks. See #1255.

**Comment by Dennisdezhangaho** [comment]
this is not resolved yet, Xcode 14 for me to do this change, and cause my app crash. I am so confused till google guide me to this page. I think I just to back to Xcode 13.4.1
